/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Nutrition = IDL.Record({
  'fatGrams' : IDL.Nat,
  'fiberGrams' : IDL.Nat,
  'calories' : IDL.Nat,
  'carbsGrams' : IDL.Nat,
  'proteinGrams' : IDL.Nat,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'priceCents' : IDL.Nat,
  'nutrition' : Nutrition,
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, Nutrition],
      [IDL.Nat],
      [],
    ),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getBlogPostsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getMenuItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Nutrition = IDL.Record({
    'fatGrams' : IDL.Nat,
    'fiberGrams' : IDL.Nat,
    'calories' : IDL.Nat,
    'carbsGrams' : IDL.Nat,
    'proteinGrams' : IDL.Nat,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'priceCents' : IDL.Nat,
    'nutrition' : Nutrition,
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, Nutrition],
        [IDL.Nat],
        [],
      ),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getBlogPostsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getMenuItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };