/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'createdAt' : Time,
  'author' : string,
  'excerpt' : string,
  'category' : string,
}
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
  'priceCents' : bigint,
  'nutrition' : Nutrition,
}
export interface Nutrition {
  'fatGrams' : bigint,
  'fiberGrams' : bigint,
  'calories' : bigint,
  'carbsGrams' : bigint,
  'proteinGrams' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addBlogPost' : ActorMethod<[string, string, string, string, string], bigint>,
  'addMenuItem' : ActorMethod<
    [string, string, bigint, string, Nutrition],
    bigint
  >,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getBlogPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'getMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'initialize' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];